apiVersion: v1
kind: Pod
metadata:
  name: prober-demo
  labels:
    app: prober-demo
spec:
  containers:
  - name: prober-demo
    image: emruzhossain/prober-demo
    imagePullPolicy: IfNotPresent
    env:
      - name: EXIT_CODE_SUCCESS
        value: "0"
      - name: EXIT_CODE_FAIL
        value: "1"
    args:
      - run-client
    ports:
      - name: http-server
        containerPort: 8080
      - name: tcp-server
        containerPort: 9090
  restartPolicy: Always
